### ISSUE TITLE
Cannot type using mobile/touchscreen

### ISSUE THREAD

**Issue by jshor** [mbenford/ngTagsInput#512]
On mobile Chrome on Android, when trying to focus the ngTagsInput directive to type in a tag, the keyboard appears and then immediately disappears. The field focuses and then immediately blurs.

You're able to focus the textbox only if you tap on the border on mobile.

**Comment by eeun** [comment]
I've had the same problem, it's only when ng-touch is used. The onTouchStart function of angular-touch is blurring the control. I've set up a plunker here to demonstrate (fails on android and on desktop chrome in device emulation):
http://embed.plnkr.co/dKijKYRpE4Xl4Hxsft1O/preview

This commit seems to fix the problem to some extent but sometimes you need to tap twice:
https://github.com/igorprado/ngTagsInput/commit/393bb7ecdcb6afed04d6f022f75a4955e5f0259f

**Comment by levity** [comment]
Thanks for the pointer to the @igorprado fork, @eeun. I'll use that until it's fixed here.

Note to anyone else trying to use that fork: the CSS file is stored in a different place, so you might have to make this change:

```diff
- @import (inline) 'bower_components/ng-tags-input/ng-tags-input.css';
+ @import (inline) 'bower_components/ng-tags-input/ngTagsInput-bower/ng-tags-input.css';
```

**Comment by bretmorris** [comment]
This fork did not solve the problem for me. Unfortunately I was forced to remove the ng-touch module all together in order to get this working. I THINK this was fine for my project but obviously others may depend on that module. Would be nice to find a solution that works nicely with ng-touch.

**Comment by sp90** [comment]
Iv'd encountered the exact same problem
:+1: 

Keyboard disappearing

**Comment by steven10172** [comment]
@igorprado thanks for the potential workaround, but I've identified the exact issue and provided a fix for ngClick: https://github.com/angular/angular.js/pull/12867

Examples:
Using ngTouch: http://embed.plnkr.co/edBdpUbM4UWI6a5Pdr7d/preview
w/o ngTouch: http://embed.plnkr.co/RHm7H2/preview
New ngTouch: http://embed.plnkr.co/4e0owINFEsWFNOap1SSs/preview

**Comment by steven10172** [comment]
@danswater I believe it was Angular v1.4.5

**Comment by mbenford** [comment]
This issue was selected to be spring-cleaned by a script. More information can be found [here](https://github.com/mbenford/ngTagsInput/issues/790).

If anyone thinks this was a mistake and this issue should be reopened, please leave a message below explaining why. Before doing so, please consider reading the [CONTRIBUTING](https://github.com/mbenford/ngTagsInput/blob/master/CONTRIBUTING.md) file.

**Comment by priyavyasamor** [comment]
@steven10172  I am still facing this issue in mobile even after applying the changes you did in angular-touch. I am using angular v 1.4.5
